### ISSUE TITLE
ask HAAS arts whether to challenge for auth on mark/transcribe routes

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#107]
to protect assets and restrict space of users entering information. Right now we don't challenge, but the hooks are in place to allow challenging without too much effort...

**Comment by pleonard212** [comment]
So, @lindsaymking says she'd like to try having *some* kind of auth challenge (CAS or non-Yale) for mark/transcribe routes.  Could we try that and see how it works?

**Comment by duhaime** [comment]
Sure thing. I'll look into this now...

**Comment by duhaime** [comment]
As it turns out, the extant Scribe app seems only to offer auth protection at the Rails router level, but the mark and transcribe routes are mounted by the React router, so this took a little consideration, but it's now live.

The expected behavior is for users who have not signed in to be challenged for authentication when they request any mark or transcribe route. Upon logging in, those users should be sent to the route they originally requested, rather than the application root (as is the case with the Rails router auth).

What do you think about the auth as it stands? If you like this, I'll merge these changes into master, otherwise I'm happy to iterate!

**Comment by pleonard212** [comment]
This looks great! 2 suggestions...

1) Remove the "Can't access your account?" mailto href on the challenge page

2) (this is hairy...) What should happen if a user clicks "Logout" while on a Mark page?  (I think Transcribe pages don't show that chrome).  Presumably we should force-redirect them to the home page, as they are no longer privileged?  But this kinda creates a "one-button ruin my day" feature.  The Logout feature could be unavailable from Mark pages, maybe?...

**Comment by duhaime** [comment]
That's an interesting question. I suppose the action on click of Logout depends on whether we're using auth for identification or for authorization. Anyone who can log in is authorized to use the app (so wouldn't require the redirect) but only those currently logged in are identifiable in a multi-session context. 

If we need to be able to identify that so and so created such and such subject, we should probably force redirect. That said, I'm not sure we need to be able to identify who made a subject (other than for retirement logic purposes, but the session-specific user ids should be sufficient for that purpose).

I'll merge these changes (minus the mailto) and mark this issue resolved, but if we decide we want to redirect users we can do that quickly (the post requests to logout are already in JS rather than Ruby).
