### ISSUE TITLE
Group level completion stats

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#128]
On our page browser page we advertise percent completion at the group level. It's possible scribe has hooks that we can use to pull group level completion stats, but if not we will probably want to configure some of that logic ourselves.

**Comment by pleonard212** [comment]
Refinement as of July 2017:

Per Group (`group`),  at bottom left inform viewers of:

1) raw number of marks made in this group
2) raw number of transcriptions made in this group
3) raw number of Plays (`subject_set`s) completed (fully marked and transcribed)
