### ISSUE TITLE
Ingest re-scans

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#130]
Hi all! We now have updated files and CSV's for each era that reflect the re-scans.   Two parts to this:

1) CSVs are here:

https://github.com/YaleDHLab/ensemble-at-yale/tree/master/project/ensemble-at-yale/subjects

(The most recent file, bundy, includes both the PDF pages and the scans.  No changes have been made to the PDF rows, but it's included for completeness of the era.)

2) Full pages and thumbnails are gziped here:

smb://storage.yale.edu/home/FC_DigitalHumanities-807001-YUL/Ensemble/2017-04DataLoad-Rescans

(On a PC: \\storage.yale.edu\home\FC_DigitalHumanities-807001-YUL\Ensemble\2017-04DataLoad-Rescans)

Finally, a note: 99% of the scans and rows are the same, but we should just dump all the old data and put in completely new stuff because there's no deterministic way of telling which images have been re-ordered, renamed, etc.  This data load should completely replace all older subjects and subject sets on the production server.

**Comment by duhaime** [comment]
@pleonard212 I uploaded all image assets to S3, dropped tables, and reran the ingestion task last night. A quick look suggests that we're only missing the images from one playbill within the Wojewodski era: [dra037-s01-b012-f136-i03-p0001.jpg](https://github.com/YaleDHLab/ensemble-at-yale/blob/master/project/ensemble-at-yale/subjects/group_stan_wojewodski.csv#L800)

Do you know if we might be able to access those images?

**Comment by pleonard212** [comment]
Great! I've uploaded the missing file and thumbnail to:

smb://storage.yale.edu/home/FC_DigitalHumanities-807001-YUL/Ensemble/2017-04DataLoad-Rescans/page-thumbs/dra037-s01-b012-f136-i03-p001.jpg

and

smb://storage.yale.edu/home/FC_DigitalHumanities-807001-YUL/Ensemble/2017-04DataLoad-Rescans/page-images/dra037-s01-b012-f136-i03-p001.jpg

**Comment by pleonard212** [comment]
Oh actually is it all pages in that play that are missing? Will update with the full set.

**Comment by pleonard212** [comment]
OK, that entire play is now on the server, ready to be added to s3.

**Comment by duhaime** [comment]
Thank you @pleonard212! We should be all set, so I'll close this one. Thanks again!

**Comment by pleonard212** [comment]
Great! Not sure if the system is still processing stuff, but looks like http://ensemble.yale.edu/ may need to be poked a bit...

**Comment by duhaime** [comment]
It looks like the rake task completed without error. If you clear your cache and re-request the page, does everything look good?

**Comment by pleonard212** [comment]
Ah, was indeed a cache issue..

**Comment by duhaime** [comment]
Excellent!
