### ISSUE TITLE
Decrease "Marking complete" threshold to 2

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#150]

**Comment by duhaime** [comment]
@pleonard212 it appears that this is the current value: https://github.com/YaleDHLab/ensemble-at-yale/blob/master/app/models/classification.rb#L90

Should we close this? Should we decrement to a single mark? It seems the updates we outlined yesterday will only increase the number of transcriptions required for each mark, they won't change the number of marks required.

**Comment by pleonard212** [comment]
Great! Closing till we hear otherwise from Haas Arts...
