### ISSUE TITLE
Errors for Facebook and Twitter logins

### ISSUE THREAD

**Issue by lindsaymking** [YaleDHLab/ensemble-at-yale#155]
Alex and I are both getting error messages when we test the Facebook and Twitter login options. Maybe some security settings have changed since we first set this up?

**Comment by duhaime** [comment]
@lindsaymking Thanks for checking this out. I just made some updates and was able to log in through both services--are you able to do so too? If not please just let me know and we can tackle this...

**Comment by lindsaymking** [comment]
It's working now--thanks for the quick fix!

**Comment by duhaime** [comment]
Awesome! My pleasure :)
