### ISSUE TITLE
Director repetition / formatting issue

### ISSUE THREAD

**Issue by alexokeefe** [YaleDHLab/ensemble-at-yale#156]
There are two issues with the director field (and the solution to the first issue may resolve the second). 
**1. Most directors are showing up multiple times for one play.**
   a. I've attached an excerpt with Constance Welch associated with the play "Jack Rabbit Flats" as an example. As you can see, "Welch, Constance" appears 21 times, while "Constance Welch" only appears once. The "last, first" format makes me think this isn't transcriptions from users. 
   b. The most is "McMullan, Frank" which appears a total of 294 times (associated with 11 plays) - there are very few "last, first" formatted entries with only 1 entry (most are 9+). 
**2. The number of "last, first" entries is slowing down the initial, basic data cleaning.** 
   a. As we've discussed, there are many fields where users input several names with commas, and I can't do a comma separation command until after all of the directors are corrected. If there is a way to avoid the last, first issues faced in the director field, it would expedite the first stages of review. 

[Welch Example.xlsx](https://github.com/YaleDHLab/ensemble-at-yale/files/2507602/Welch.Example.xlsx)

Thank you so much for your help with this! 
-AOK

**Comment by duhaime** [comment]
Thanks @alexokeefe! I'll take a look at this in just a moment...

**Comment by alexokeefe** [comment]
Seems good now, Doug! I'll let you know if anything else pops up. Thanks again! -AOK

**Comment by duhaime** [comment]
Woohoo! Please feel free to reach out if anything else seems strange in the data...
