### ISSUE TITLE
How to handle playbill information split across multiple pages?

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#16]
Some playbills have information split across multiple pages, e.g.:
![screen shot 2016-06-24 at 12 48 29 pm](https://cloud.githubusercontent.com/assets/4801116/16344358/2f48792e-3a0a-11e6-8b31-bedef10970be.png)

We should discuss the way we want to handle these cases...

**Comment by pleonard212** [comment]
This is indeed an interesting question. It would probably be labor-intensive to have a student go through all pages and see where this occurred. So I'm leaning towards a "flag" option that users can hit to indicate there's a scanning problem.  I think this is an affordance within scribeAPI?  

Once we have reports that there's a problem with a program, we can manually merge 2x pages back into one larger sheet using photoshop, and queue the updated program for inclusion in the next batch of ingests.

**Comment by lindsaymking** [comment]
There might be other problems with programs that we haven't anticipated, so I agree that flagging is a good option that covers a multitude of concerns. The manual work of putting things back together, in the right order, etc. can then happen later, as Peter suggests.

**Comment by pleonard212** [comment]
I manually re-combined a few images in photoshop on the last QA check; happy to do the same for other ones that get flagged.

**Comment by duhaime** [comment]
Flagging sounds perfect; I'll close this issue
