### ISSUE TITLE
Usability Questions and Feedback

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#164]
These are just some UX questions that came up during the Transcribe-a-thon. 

- [x] Differentiate the colors of the Title box and Actor box. Maybe a red #e60000 for Title?
- [ ] Add help text for lists that remind users to mark each individual name of a list, i.e. chorus members.
- [ ] Add help text for names that are split due to line breaks reminding them that they can simply mark just one part of the name. 
- [ ] This is a nice to have: Because programs aren't always scanned straight, it would be nice to nudge rotate the box (left and right) by 1 degree just to keep the regions from overlapping others.

**Comment by alexokeefe** [comment]
I have added help text review to our to do list- @lindsaymking 

Following up on the proposed red box for title. We recently had someone mark all actors with title boxes on accident due to current color similarity.

**Comment by duhaime** [comment]
@alexokeefe Have you by chance had a moment to draft some help text for this one?

If so, I think the quickest change will be to add this help text to the tutorial text that appears when one first enters the Mark stage. What do you think about that solution?

I don't think we want to build a rotation widget as that would affect all of the rectangle drawing business too, but the color is easy enough to change...

**Comment by duhaime** [comment]
closing this one as we're moving to Project Builder...
