### ISSUE TITLE
Allow users to transcribe from the marking step

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#166]
as they can transcribe from the marking step

**Comment by duhaime** [comment]
@alexokeefe was the goal here to allow users to *mark* from the *transcription* step?

**Comment by alexokeefe** [comment]
@duhaime I think so - users were often hoping to go back to the marking screen from transcribing. This was mostly the case with users at transcribe-a-thons who noticed glaring issues (like one large box around a lot of names, etc.) Once we had a user accidentally mark all of the actors with the wrong box type, and they wanted to go back and correct it. In that case I was able to adjust the URL to get them back to marking for that program, but they wouldn't have been able to do it themselves.

**Comment by duhaime** [comment]
Excellent thanks for following up. I suppose we just need a button that links them back in that case. We can hook that up...

**Comment by duhaime** [comment]
closing this one as we're moving to Project Builder...
