### ISSUE TITLE
Create list of multiple plays for removal

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#170]
Remove programs that are not plays and/or are multiple.

**Comment by pleonard212** [comment]
subject_set_id=5919e041adb8170833fb5100
subject_set_id=5919e039adb8170833fb50f5

**Comment by lindsaymking** [comment]
Looking back at the spreadsheet, the only one I found that wasn't marked with a Y for "non-theatrical" was the All Army Show, and that's one you've already noted. The USO cover is misleading, but it is actually a one-act play. The rest of the non-play programs appear to have been suppressed when the CSV was created. 

The multi-play ones may need to be flagged from within Ensemble. Here's one example: subject_set_id=5919e18cadb8170833fb52c2
I clicked "flag an issue" but I don't actually know what that does...

**Comment by alexokeefe** [comment]
Adding one recently found in Dept of Drama era: 
5919e18cadb8170833fb52c2 | Titles: Another Summer & Mongo the People

**Comment by duhaime** [comment]
@alexokeefe and @lindsaymking should we go ahead and remove this list of plays from the UI?

**Comment by lindsaymking** [comment]
Yes, please do!

**Comment by duhaime** [comment]
Excellent, this is closed via:

```
db.subject_sets.remove({ '_id': { $in: [ ObjectId('5919e041adb8170833fb5100'), ObjectId('5919e039adb8170833fb50f5'), ObjectId('5919e18cadb8170833fb52c2'), ObjectId('5919e18cadb8170833fb52c2') ] } }, false )
```
