### ISSUE TITLE
Facebook won't allow log in

### ISSUE THREAD

**Issue by alexokeefe** [YaleDHLab/ensemble-at-yale#173]
Just tried to login using Facebook to try and be different users when transcribing - Facebook gave error. See attached.
![fb ensemble error](https://user-images.githubusercontent.com/44412803/52081825-32778c00-2569-11e9-8fb1-43b67bfde159.png)

**Comment by duhaime** [comment]
Thanks for this @alexokeefe. Facebook evidently now requires use of the HTTPS protocol for the user of its auth layer. We can set that up, but it will require some testing and implementation time + maintenance.

@pleonard212 This may be a good opportunity for us to work with internal IT to get them to provision and manage SSL certs. Should I spend some time digging in on this?

**Comment by pleonard212** [comment]
Sure, I think that makes sense, as HTTPS will only become more important.  Should we temporarily disable the Facebook login button?

**Comment by duhaime** [comment]
This is all set now via nginx config. Note that the global sign docs outline two different values for the list of pem files in the combined cert. The proper combined order is:

cert emailed from global sign
intermediate (organizational) cert
r1 root (organizational) cert

assuming one is using organizational certs.
