### ISSUE TITLE
"Bad Region" not resetting

### ISSUE THREAD

**Issue by alexokeefe** [YaleDHLab/ensemble-at-yale#178]
Hi @duhaime - putting in this reminder based on the issue I showed you during the transcribe-a-thon Friday. The "Bad Region" button is holding it's yes/no command when transcribing. So when you click "Bad Region" for one box, it carries to the next until you click it again. Let me know if you need more info!

**Comment by duhaime** [comment]
Thanks @alexokeefe I should be able to take a look later this week...

**Comment by duhaime** [comment]
done!
