### ISSUE TITLE
Facebook won't allow log in (again)

### ISSUE THREAD

**Issue by alexokeefe** [YaleDHLab/ensemble-at-yale#179]
See previous issue Facebook won't allow log in #173.  
As of the 4.12 the Facebook login is not working again. 

@lindsaymking @pleonard212 @duhaime what do we think about eliminating Facebook as a log in option? Upside - no more trouble shooting. Possible downside - we do try and promote the event on Facebook so there are possibilities a user from that platform would want that option. 

Is there anyway to know if we've had anyone use FB to log into Ensemble before? If no one has we have an easier answer I think...

**Comment by duhaime** [comment]
closing this one as we're moving to Project Builder...
