### ISSUE TITLE
Link update on About page

### ISSUE THREAD

**Issue by alexokeefe** [YaleDHLab/ensemble-at-yale#182]
I was copying text from the current Ensemble@Yale about page to the Zooniverse site, and caught that the link for Yale Rep is broken.

This is the page: [http://ensemble.yale.edu/#/about](http://ensemble.yale.edu/#/about)
This is the correct Yale Rep link: [https://www.yalerep.org/](https://www.yalerep.org/)

No rush - just didn't want to forget to put an issue in.

**Comment by duhaime** [comment]
Thanks @alexokeefe -- if it's alright it'd be best to update this when we implement the other forthcoming changes

**Comment by alexokeefe** [comment]
Of course! No problem at all @duhaime.
