### ISSUE TITLE
Spacing on About page

### ISSUE THREAD

**Issue by lindsaymking** [YaleDHLab/ensemble-at-yale#36]
Add white space between paragraphs and headings

**Comment by duhaime** [comment]
Thanks @lindsaymking! I don't have the images yet, but spacing wise how does this look: http://52.25.171.124/#/about ?

**Comment by pleonard212** [comment]
Looks great to me!

**Comment by lindsaymking** [comment]
Much clearer!

**Comment by duhaime** [comment]
Excellent! 👊
