### ISSUE TITLE
Write Mark + Transcribe Tutorials

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#45]

**Comment by lindsaymking** [comment]
Done!

**Comment by duhaime** [comment]
The changes in #71 and #72 are now merged and deployed. 

I think the only thing we need is copy for the transcribe tutorial (it doesn't display by default but will display if users click the `?` icon on the right side of the page). The text for this modal is set within: [yale-transcribe-tutorial-text.cjsx](https://github.com/YaleDHLab/ensemble-at-yale/blob/master/app/assets/javascripts/components/tutorial-text/yale-transcribe-tutorial-text.cjsx)

**Comment by lindsaymking** [comment]
Oops, I thought I'd put that in before. Just added it!

**Comment by pleonard212** [comment]
Think we're done here...
