### ISSUE TITLE
Investigate what the Admin Dashboard can (and can't) do...

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#55]

**Comment by duhaime** [comment]
One possible ready-to-hand admin dashboard could come from MongoDB Compass, which has lots of data visualizations that link right to documents that users can modify with a point and click interface:

![screen shot 2016-11-07 at 5 07 01 pm](https://cloud.githubusercontent.com/assets/4801116/20077987/b90dfa36-a50c-11e6-81ac-ab09c36b793b.png)

It's not built into Scribe, but is very flexible and gives at-a-glance overviews of all data fields, including the percent of subject sets that have been retired, the content of each subject set, and so forth. I've found it super helpful while developing, and could see the app being helpful for others on the admin side...

**Comment by duhaime** [comment]
Closing this issue for the present. We can reopen if there are features we need from the admin dashboard that Compass or the Scribe dashboard can't provide...
