### ISSUE TITLE
UX QA 1.3 - Final tweaks

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#62]
- [x] Reduce weight on Bold type: .major-button { font-weight: 500; }
- [x] MARK page: For multi-page programs, have the slider appear by default. Can we add a drop shadow behind the right edge of the gray lightbox bg?
- [x] .right-column .task-area.mark { font-size: .9em; }
- [x] Gray light box right corner (?)-icon color: #ffffff
- [x] Gray light box page view - is there any way the page can fill the cell, w/ the corners under the page number? Let's reduce the border stroke just 2px. 
- [x] .classifier .right-column .task-area .workflow-task .answer { font-size: 13px; }
- [x] Transcribe: decrease instruction text content width to make room for the (?) help icon on the right corner of the modal.   
![screen shot 2016-11-09 at 3 00 00 pm](https://cloud.githubusercontent.com/assets/25487/20152702/4f3c4b4e-a68d-11e6-8456-ef20194c6a8a.png)

HOME: 
- [x] .hero-overlay-text { line-height: 1.4em; font-family: Mallory; } 
- [x] .hero-overlay-title { font-family: YaleNew; }  -- for some reason it looks like Times?
- [x] Era order: Move Brustein Era so that it is to the right of the Lloyd Richards Era.
- [x] For the rollover image in the third row on the right, please move down the program cover image so that we can see "Yale University Theatre" type. 
- [x] "Log in" - in title case

Collection:
- [x] .mark-button     { font-family: Mallory;}
- [x] .transcribe-button { font-familh: Mallory; }

**Comment by duhaime** [comment]
Excellent! The order of the landing page cards is now set by the order column in the `projects/ensemble-at-yale/subjects/groups.csv` file, so admin users can configure the order in which they want those cards to appear.

**Comment by duhaime** [comment]
After considering the vertical and horizontal aspect ratios of thumbnails, we decided to temporarily shelf the full-container thumbnail idea, as filling the thumbnail container with radically varying aspect ratios will cause heavy cropping that might hide metadata elements of interest. This might be something to revisit in the future if users have a hard time identifying which pages are of interest for a particular playbill...

**Comment by duhaime** [comment]
closed via #68
