### ISSUE TITLE
"Done" check box on mark rectangles disappears on dark programs

### ISSUE THREAD

**Issue by lindsaymking** [YaleDHLab/ensemble-at-yale#67]
The check box that appears at the bottom of the rectangle a user marks so that they can indicate it as "done" is invisible if the program is dark in color. Most of the time this will not be a problem, but when it is, you really can't see where to click.

**Comment by duhaime** [comment]
Yes, I thought this would become a problem. We could conditionalize the overlay colors as a function of playbill cover lightness darkness, but that would be a decent amount of work. A simpler and probably more successful strategy might be to provide a background color for that box, ala:

![screen shot 2016-11-10 at 12 18 42 pm](https://cloud.githubusercontent.com/assets/4801116/20186898/dbce6c74-a73f-11e6-9890-5329689fe260.png)

How would that be?

**Comment by mongmedia** [comment]
Looks good!
Monica



On Nov 10, 2016, at 12:19 PM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I thought this would become a problem. We could conditionalize the overlay colors as a function of playbill cover lightness darkness, but that would be a decent amount of work. A simpler and probably more successful strategy might be to provide a background color for that box, ala:

[screen shot 2016-11-10 at 12 18 42 pm]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_4801116_20186898_dbce6c74-2Da73f-2D11e6-2D9890-2D5329689fe260.png&d=CwMFaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=r8poZYiiorN0dwkcUsGivI0MEVxJU_WqEKZSiwqE1YE&m=SBQRqh1wiVNI9bvOdz71GU7pRp83MQOIpMlOa6U2HV4&s=_8-9Vph6CjYZCMK5CCCzhFWzQS-GvimPYtXcmQD3xq0&e=>

How would that be?

**Comment by lindsaymking** [comment]
That works!

**Comment by duhaime** [comment]
Excellent :)
