### ISSUE TITLE
Possible hiccup in 'Era' hover imgs

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#69]
I'm getting some improbable hover-state images when I hover over the eras... for example the last one, James Bundy, hover-states to http://ensemble.yale.edu/assets/6-YaleDrama.jpg which is actually from 1949.  Possible that the recent ordering logic change occasioned a disconnect between the box and the correct hover img?

**Comment by duhaime** [comment]
Ah yes, I'm reingesting the subjects with new order keys to make the app match the mocks, so this should be all set once this rake task completes...

**Comment by duhaime** [comment]
Does this look good now? http://ensemble.yale.edu/#/

**Comment by mongmedia** [comment]
The rollover on row 3 right side can be swapped out and replaced with the Divine Comedy image. You can refer to XD comp for positioning.

Thanks,
Monica

[cid:FBFD2BBE-D938-4EB9-A516-51C38891F23B@frontier.com]


On Nov 11, 2016, at 3:36 PM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this look good now? http://ensemble.yale.edu/#/

**Comment by pleonard212** [comment]
Thx!
