### ISSUE TITLE
Transcribe workflow tool

### ISSUE THREAD

**Issue by lindsaymking** [YaleDHLab/ensemble-at-yale#74]
The question mark that would bring up a tutorial or help page for the Transcribe workflow only appears sometimes on the boxes that prompt users to "Type the title of the play," for example--it looks like it appears on composite tools but not text tools. It should be on all of them.

**Comment by duhaime** [comment]
Excellent, that's no problem to configure. Should the help text that's displayed when users click that icon be the same for all transcribe tools, or tool specific? If the help is to be tool-specific, should the help box display the content of the `help` key for the tool in `transcribe.json`?

**Comment by duhaime** [comment]
You were exactly right, the text tool wasn't passing the props required to display the button that toggles the tutorial. This should be all set now.
