### ISSUE TITLE
Do the help files need cleanup?

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#83]
Monica found that some of the help files in the Mark step seem to remark on aspects of the Transcribe workflow. Here's the help for Dates, for example:

![screen shot 2016-12-12 at 2 43 02 pm](https://cloud.githubusercontent.com/assets/4801116/21143548/2c3ec778-c115-11e6-9c79-db87842baaf8.png)

This text content is evidently set by the file specified by the `help` key in: project/ensemble-at-yale/workflows/mark.json

```
{  
    "type":"rectangleTool",
    "label":"Dates",
    "color":"#2EC6EA",
    "generates_subject_type":"ey_dates",
    "help":{  
       "file":"ey_dates"
    }
 }
```

Currently the help file for the Date portion of the Mark workflow is ey_dates, which contains the text displayed in the help modal above. Should we do a quick sweep of these help files to make sure they're all up to date?

**Comment by pleonard212** [comment]
Yes! We noticed this too and we're trying to trace where the spurious help was coming from.  there is also a similar issue with the help for transcription too...

**Comment by duhaime** [comment]
@pleonard212 @lindsaymking Do the help files look okay now? They seem to be all set now (at least the cases I've seen): 
![screen shot 2017-01-03 at 10 08 20 am](https://cloud.githubusercontent.com/assets/4801116/21611835/953ff9d0-d19c-11e6-80d1-ce185d602b78.png)

**Comment by lindsaymking** [comment]
From what I can see, doing some marking and transcribing, things look good!

**Comment by duhaime** [comment]
Excellent! I'll mark this as resolved, and we can reopen if needed...
