### ISSUE TITLE
Change cursor for resize handles

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/ensemble-at-yale#84]
To indicate to the user that a Mark box is resizable, consider switching our cursor to `nesw-resize` or `nwse-resize` (as appropriate) for the black dots at the four corners. (Currently it's `grab`, which is appropriate for the sides but not the corners).

**Comment by duhaime** [comment]
@pleonard212 How do the new handles look? The corners are bigger now, and I switched the cursor inside the box to move, as that seemed to be the behavior there. We could do something like an nesw-resize for the corners, but each corner can go in all 4 directions, so I'm not sure what's best...
