### ISSUE TITLE
Boolean toggle on Mark stage

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/ensemble-at-yale#85]
for "Is there anything left to mark"

**Comment by mongmedia** [comment]
Have a comp for this...wanna get your feedback/consensus on the language:

"Is marking complete for this program?" - is that clear enough?

"Report an issue" - another alternative for the user feedback button.

Thanks!
![7 mark page revised last step - on](https://cloud.githubusercontent.com/assets/25487/21324986/0ea44800-c5f2-11e6-8971-35c0e5726e42.png)
![7 mark page revised last step off](https://cloud.githubusercontent.com/assets/25487/21324987/0ea507b8-c5f2-11e6-85b3-560acfcadbc2.png)
