### ISSUE TITLE
Home Page: Updated Copy

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/ensemble-at-yale#95]
This is the home page with alternate text for the hero image as well as the section with the eras. Let me know what the consensus is on the new language.

Also, regarding the "Login" link, let's make it title case and float it towards the right about 80px from the edge. Just want to try something that doesn't give it the same hierarchical position as the other nav links.

Thanks,
Monica

![web 1280 home - productions 1 2](https://cloud.githubusercontent.com/assets/25487/21325382/1a6f790a-c5f4-11e6-827d-69ca9295b4bc.png)

**Comment by lindsaymking** [comment]
New thought: what if we remove the small text from the hero image and put it below (above the eras) instead, for example as "Browse 90 years of programs to see what's available to mark or transcribe"? You could leave "Get started" to prompt users to click one of the buttons.
